name: Main Workflow

on: 
  push: 
    branches: 
      - main

jobs: 
  call-reusable-workflow:
    uses: lgodet/workflow-reusable-example/.github/workflows/reusable-workflow.yml@main
    with:
      name: 'Github User'
      run-tests: true

      
